export const BASE_URL = ''
export const BASE_LOCAL_URL = 'http://localhost:3000'
// export const DEPARTMENT_URL = BASE_LOCAL_URL || BASE_URL + 'department'
export const DEPARTMENT_URL = BASE_LOCAL_URL + '/department'
export const STAFF_URL = BASE_LOCAL_URL + '/staff'
export const NEWS_URL = BASE_LOCAL_URL + '/news'
export const SENDER_URL = BASE_LOCAL_URL + '/sender'

export const CLOUD_URI = 'https://api.cloudinary.com/v1_1/duytrann/image/upload'
export const PRESENT = 'ml_default'
